server:
  port: 9090

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/deepknow?useUnicode=true&serverTimezone=GMT%2B8&useSSL=false&characterEncoding=utf8
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.gpy.deepdemo.entity
  type-enums-package: com.gpy.deepdemo.enums
  configuration:
    map-underscore-to-camel-case: true
    lazy-loading-enabled: true
    aggressive-lazy-loading: true
    cache-enabled: true
  global-config:
    db-config:
      db-type: mysql
      table-underline: true
